server:
  http:
    addr: 0.0.0.0:8181

db:
  driver: mysql
  source: "root:123456@tcp(127.0.0.1:3306)/harmoni_notification?parseTime=True&timeout=10s"
  connMaxLifeTime: 3600s
  maxOpenConn: 4
  maxIdleConn: 4

messageQueue:
  rabbitMQ:
    username: guest
    password: guest
    host: 127.0.0.1
    port: 5672
    vhost:

etcd:
  addr:
    - "127.0.0.1:2379"

log:
  level: "debug"
  path: "./log/server.log"

app:
  startTime: "2023-10-27"
  appId: 2
  locale: zh
