app:
  addr: 0.0.0.0:8080
  debug: false
  base_url: http://localhost
  start_time: 2023-08-01
  app_id: 1
  locale: zh
server:
  http:
    addr: 0.0.0.0:8080
  grpc:
    addr: 0.0.0.0:8082
auth:
  token_expire: 5m
  refresh_token_expire: 72h
  secret: JWTSECRET

db:
  driver: mysql
  source: "root:123456@tcp(db:3306)/harmoni?parseTime=True&timeout=10s"
  conn_max_life_time: 1h
  max_open_conn: 4
  max_idle_conn: 4

log:
  level: debug # debug | error | warn | info
  path: ./log/harmoni.log

redis:
  ip: rdb
  port: 6379
  # password: password
  database: 0
  pool_size: 2
  read_timeout: 5s
  write_timeout: 5s
etcd:
  addr: etcd:2379
  # username:
  # password:

email:
  host: google.com
  port: 456
  user_name: example@gmail.com
  password: 1234
  from_name: noreply
  code_ttl: 5m

messageQueue:
  rabbitmq:
    username: guest
    password: guest
    host: rabbitmq
    port: 5672
    vhost:

fileStorage:
  defaultAvatar: default.png
  uploadSessionTimeout: 1h # unit is s,m,h
  policy:
    type: local # storage type, only local for now
    bucketName: ./static # storage path for local type
    maxSize: 104857600 # max upload size per file
    option:
      # allowed file extension
      # if not present, all extension is allowd
      fileType:
        - .jpg
        - .png
      chunkSize: 5242880 # The minimum required file size in chunked uploading.
