app:
  # addr: 0.0.0.0:8080
  debug: false

auth:
  tokenExpire: 3600
  # secret:

db:
  # driver:
  # source:
  conn_max_life_time: 1h

log:
  level: debug # debug | error | warn | info
  path: ./log/harmoni.log

redis:
  # ip:
  # port:
  # password:
  database: 0
  poolSize: 2
  readTimeout: 5s
  writeTimeout: 5s
