app:
  addr: 0.0.0.0:8080
  debug: false

auth:
  token_expire: 5m
  refresh_token_expire: 72h
  secret: JWTSECRET

db:
  driver: mysql
  source: "user:password@tcp(localhost:3306)/database?parseTime=True&timeout=10s"
  conn_max_life_time: 1h
  max_open_conn: 4
  max_idle_conn: 4

log:
  level: debug # debug | error | warn | info
  path: ./log/harmoni.log

redis:
  ip: localhost
  port: 6379
  password: password
  database: 0
  pool_size: 2
  read_timeout: 5s
  write_timeout: 5s

email:
  host: google.com
  port: 456
  user_name: example@gmail.com
  password: 1234
  from_name: noreply
  code_ttl: 5m

message_queue:
  rabbitmq:
    username:
    password:
    host:
    port:
    vhost:
